logging:
  level:
    org.hibernate.SQL: debug

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:gestorvotacao
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9095

apis:
  CPFUrl: https://user-info.herokuapp.com/users/